# Generated by Django 3.0.7 on 2020-06-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogtitle', models.CharField(max_length=100)),
                ('blogdescription', models.CharField(max_length=500)),
                ('blogtime', models.DateTimeField(auto_now=True)),
                ('blogimage', models.ImageField(upload_to='blog/images')),
            ],
        ),
    ]
